"""Tests for the BATSRUS reader using synthetic fixtures.

Fixtures are generated by ``scripts/generate_batsrus_fixture.py`` and
committed under ``tests/data/batsrus-synthetic/``.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
from numpy.testing import assert_allclose

from pypic.readers.batsrus import (
    open_batsrus,
    parse_header,
    parse_param_in,
)
from pypic.readers.batsrus._field_map import (
    FIELD_NAME_MAP,
    SKIP_FIELDS,
    convert_fields_to_si,
    is_normalized,
    unit_factor,
)
from pypic.readers.batsrus._grid import is_uniform_idl

DATA_DIR = Path(__file__).parent / "data" / "batsrus-synthetic"
IDL_DIR = DATA_DIR / "idl-uniform"
HDF5_DIR = DATA_DIR / "hdf5-uniform"
AMR_DIR = DATA_DIR / "hdf5-amr"
IDL_AMR_DIR = DATA_DIR / "idl-amr"

# Harris sheet parameters (must match generate_batsrus_fixture.py)
B0 = 1.0
DELTA = 2.0
RHO0 = 1.0
P0 = 0.1
XMIN, XMAX = -8.0, 8.0
YMIN, YMAX = -8.0, 8.0
NX, NY = 16, 16
DX = (XMAX - XMIN) / NX


class TestFieldMap:
    """Unit tests for field name mapping and unit conversion."""

    def test_canonical_names_cover_mhd_basics(self) -> None:
        assert FIELD_NAME_MAP["Rho"] == "rho_m"
        assert FIELD_NAME_MAP["Bx"] == "B1"
        assert FIELD_NAME_MAP["Ux"] == "V1"
        assert FIELD_NAME_MAP["P"] == "P"

    def test_hyp_is_skipped(self) -> None:
        assert "Hyp" in SKIP_FIELDS

    def test_normalized_detection(self) -> None:
        assert is_normalized("normalized units")
        assert is_normalized("  Normalized  ")
        assert not is_normalized("Mp/cc km/s nT")

    @pytest.mark.parametrize(
        ("unit_str", "expected"),
        [
            ("nT", 1e-9),
            ("km/s", 1e3),
            ("nPa", 1e-9),
            ("R", 1.0),
        ],
    )
    def test_unit_factor(self, unit_str: str, expected: float) -> None:
        assert_allclose(unit_factor(unit_str), expected, rtol=1e-10)

    def test_density_to_si(self) -> None:
        from scipy import constants

        factor = unit_factor("Mp/cc")
        rho_mpccc = 5.0
        rho_si = rho_mpccc * factor
        expected = 5.0 * 1e6 * constants.m_p
        assert_allclose(rho_si, expected, rtol=1e-10)

    def test_convert_fields_noop_for_normalized(self) -> None:
        fields = {"rho_m": np.array([1.0, 2.0])}
        var_names = ("Rho",)
        unit_names = ("normalized",)
        result = convert_fields_to_si(fields, var_names, unit_names)
        assert_allclose(result["rho_m"], [1.0, 2.0])

    def test_convert_fields_applies_factors(self) -> None:
        fields = {"B1": np.array([5.0])}
        var_names = ("Bx",)
        unit_names = ("nT",)
        result = convert_fields_to_si(fields, var_names, unit_names)
        assert_allclose(result["B1"], [5e-9], rtol=1e-10)


class TestHeader:
    """Test .h header parsing."""

    def test_parse_synthetic_header(self) -> None:
        header = parse_header(IDL_DIR / "z=0_mhd_1_n00000000.h")
        assert header.ndim == 2
        assert header.geometry == "cartesian"
        assert header.n_cells == NX * NY
        assert header.is_binary is True
        assert header.n_byte_real == 8
        assert header.n_plot_var == 12
        assert "Rho" in header.var_names
        assert "Bx" in header.var_names

    def test_header_domain_bounds(self) -> None:
        header = parse_header(IDL_DIR / "z=0_mhd_1_n00000000.h")
        assert_allclose(header.domain_min, (XMIN, YMIN))
        assert_allclose(header.domain_max, (XMAX, YMAX))

    def test_header_gamma_parameter(self) -> None:
        header = parse_header(IDL_DIR / "z=0_mhd_1_n00000000.h")
        assert header.n_param == 1
        assert_allclose(header.param_values[0], 5.0 / 3.0, rtol=1e-4)

    @pytest.mark.skipif(
        not (
            Path("examples/batsrus-blast2d-ascii") / "z=0_mhd_1_t00000000_n00000000.h"
        ).exists(),
        reason="Real blast2d example not available",
    )
    def test_parse_real_blast_header(self) -> None:
        header = parse_header(
            Path("examples/batsrus-blast2d-ascii/z=0_mhd_1_t00000000_n00000000.h")
        )
        assert header.ndim == 2
        assert header.n_cells == 1024
        assert header.output_format == "ascii"

    @pytest.mark.skipif(
        not (
            Path("examples/batsrus-earth2d-amr-idl") / "z=0_mhd_1_n00000000.h"
        ).exists(),
        reason="Real earth2d-amr example not available",
    )
    def test_parse_real_earth_header(self) -> None:
        header = parse_header(
            Path("examples/batsrus-earth2d-amr-idl/z=0_mhd_1_n00000000.h")
        )
        assert header.ndim == 2
        assert header.n_cells == 3072
        assert header.n_param == 3
        assert "xsi" in header.param_names
        assert "nT" in header.unit_string


class TestParamIn:
    """Test PARAM.in parsing."""

    def test_parse_synthetic_param(self) -> None:
        config = parse_param_in(IDL_DIR / "PARAM.in")
        assert config.io_units == "NONE"
        assert config.normalization_type == "NONE"
        assert_allclose(config.gamma, 5.0 / 3.0, rtol=1e-10)

    def test_grid_bounds(self) -> None:
        config = parse_param_in(IDL_DIR / "PARAM.in")
        assert_allclose(config.domain_min[:2], (XMIN, YMIN))
        assert_allclose(config.domain_max[:2], (XMAX, YMAX))

    @pytest.mark.skipif(
        not (Path("examples/batsrus-earth2d-amr-idl") / "PARAM.in").exists(),
        reason="Real earth2d-amr example not available",
    )
    def test_parse_real_earth_param(self) -> None:
        config = parse_param_in(Path("examples/batsrus-earth2d-amr-idl/PARAM.in"))
        assert config.coord_system == "GSM"
        assert config.body_radius == 2.5
        assert_allclose(config.solar_wind["bz_dim"], -5.0)

    @pytest.mark.skipif(
        not (Path("examples/batsrus-blast2d-ascii") / "PARAM.in").exists(),
        reason="Real blast example not available",
    )
    def test_parse_blast_param(self) -> None:
        config = parse_param_in(Path("examples/batsrus-blast2d-ascii/PARAM.in"))
        assert config.io_units == "NONE"
        assert config.description == "2D MHD blast wave — ASCII IDL output test"


class TestIDLUniform:
    """Test IDL per-cell reader with uniform synthetic grid."""

    def test_reads_with_canonical_names_and_shapes(self) -> None:
        reader, _ = open_batsrus(IDL_DIR)
        ds = reader.read_timestep(IDL_DIR, 0)
        assert ds.has_field("B1")
        assert ds.has_field("rho_m")
        assert ds.has_field("V1")
        assert ds.has_field("P")
        assert not ds.has_field("Hyp")
        for name in ds.field_names():
            assert ds[name].shape == (NX, NY), f"{name} has wrong shape"

    def test_harris_physics(self) -> None:
        reader, _ = open_batsrus(IDL_DIR)
        ds = reader.read_timestep(IDL_DIR, 0)
        # Harris Bx profile
        bx = ds["B1"]
        iy_mid = NY // 2
        assert_allclose(bx[:, iy_mid], 0.0, atol=0.3)
        assert bx[:, -1].mean() > 0.9
        assert bx[:, 0].mean() < -0.9
        # Uniform density and pressure
        assert_allclose(ds["rho_m"], RHO0, rtol=1e-10)
        assert_allclose(ds["P"], P0, rtol=1e-10)

    def test_grid_info(self) -> None:
        _, config = open_batsrus(IDL_DIR)
        assert config.grid.dimensions == (NX, NY)
        assert_allclose(config.grid.spacing, (DX, DX))

    def test_no_nan_fields(self) -> None:
        reader, _ = open_batsrus(IDL_DIR)
        ds = reader.read_timestep(IDL_DIR, 0)
        for name in ds.field_names():
            assert not np.any(np.isnan(ds[name])), f"{name} contains NaN"


class TestHDF5Uniform:
    """Test HDF5 BATL reader with uniform synthetic grid."""

    def test_reads_with_correct_shapes_no_nan(self) -> None:
        reader, _ = open_batsrus(HDF5_DIR)
        ds = reader.read_timestep(HDF5_DIR, 0)
        for name in ds.field_names():
            assert ds[name].shape == (NX, NY), f"{name} has wrong shape"
            assert not np.any(np.isnan(ds[name])), f"{name} contains NaN"

    def test_cross_format_match_idl(self) -> None:
        """IDL and HDF5 produce identical fields for the same physics."""
        reader_idl, _ = open_batsrus(IDL_DIR)
        reader_hdf, _ = open_batsrus(HDF5_DIR)
        ds_idl = reader_idl.read_timestep(IDL_DIR, 0)
        ds_hdf = reader_hdf.read_timestep(HDF5_DIR, 0)

        for name in ds_idl.field_names():
            if not ds_hdf.has_field(name):
                continue
            assert_allclose(
                ds_idl[name],
                ds_hdf[name],
                rtol=1e-10,
                err_msg=f"Cross-format mismatch for {name}",
            )


class TestHDF5AMR:
    """Test HDF5 BATL reader with AMR regridding."""

    def test_output_at_finest_resolution(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0)
        # Finest dx = 0.5, domain = 16x16 -> 32x32
        assert ds["B1"].shape == (32, 32)

    def test_no_nan_after_regrid(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0)
        for name in ds.field_names():
            assert not np.any(np.isnan(ds[name])), f"{name} contains NaN"

    def test_coarse_cells_filled(self) -> None:
        """Coarse cells are expanded via nearest-neighbor fill."""
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0)
        rho = ds["rho_m"]
        # All cells should have the uniform density value
        assert_allclose(rho, RHO0, rtol=1e-10)

    def test_harris_profile_preserved(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0)
        bx = ds["B1"]
        # Top row should be near +B0
        assert bx[:, -1].mean() > 0.9
        # Bottom row should be near -B0
        assert bx[:, 0].mean() < -0.9


class TestOpenBatsrusDetection:
    """Test format auto-detection in ``open_batsrus``."""

    def test_detects_idl(self) -> None:
        _, config = open_batsrus(IDL_DIR)
        assert config.model_name == "BATSRUS"
        assert config.model_type == "MHD"

    def test_detects_hdf5(self) -> None:
        _, config = open_batsrus(HDF5_DIR)
        assert config.model_name == "BATSRUS"

    def test_available_timesteps_idl(self) -> None:
        reader, _ = open_batsrus(IDL_DIR)
        steps = reader.available_timesteps(IDL_DIR)
        assert 0 in steps

    def test_available_timesteps_hdf5(self) -> None:
        reader, _ = open_batsrus(HDF5_DIR)
        steps = reader.available_timesteps(HDF5_DIR)
        assert 0 in steps


class TestIDLAMR:
    """Test IDL per-cell reader with AMR synthetic grid."""

    def test_output_at_finest_resolution(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds = reader.read_timestep(IDL_AMR_DIR, 0)
        assert ds["B1"].shape == (32, 32)

    def test_no_nan_after_regrid(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds = reader.read_timestep(IDL_AMR_DIR, 0)
        for name in ds.field_names():
            assert not np.any(np.isnan(ds[name])), f"{name} contains NaN"

    def test_uniform_density(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds = reader.read_timestep(IDL_AMR_DIR, 0)
        assert_allclose(ds["rho_m"], RHO0, rtol=1e-10)


class TestTargetResolutionHDF5:
    """Test target_resolution parameter for HDF5 AMR reader."""

    def test_coarsens_output(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0, target_resolution=1.0)
        assert ds["B1"].shape == (16, 16)

    def test_none_is_finest(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds_default = reader.read_timestep(AMR_DIR, 0)
        ds_explicit = reader.read_timestep(AMR_DIR, 0, target_resolution=None)
        for name in ds_default.field_names():
            assert_allclose(ds_default[name], ds_explicit[name], rtol=1e-15)

    def test_preserves_uniform_density(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0, target_resolution=1.0)
        assert_allclose(ds["rho_m"], RHO0, rtol=1e-10)

    def test_preserves_harris_profile(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0, target_resolution=1.0)
        bx = ds["B1"]
        assert bx[:, -1].mean() > 0.9
        assert bx[:, 0].mean() < -0.9

    def test_no_nan_at_coarse_resolution(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0, target_resolution=1.0)
        for name in ds.field_names():
            assert not np.any(np.isnan(ds[name])), f"{name} contains NaN"

    def test_intermediate_snaps_to_nearest(self) -> None:
        """A target_resolution between levels snaps to the nearest valid dx."""
        reader, _ = open_batsrus(AMR_DIR)
        # Levels are 0.5 and 1.0. Target 0.7 is closer to 0.5.
        ds = reader.read_timestep(AMR_DIR, 0, target_resolution=0.7)
        assert ds["B1"].shape == (32, 32)
        # Target 0.8 is closer to 1.0.
        ds = reader.read_timestep(AMR_DIR, 0, target_resolution=0.8)
        assert ds["B1"].shape == (16, 16)

    def test_grid_spacing_matches_target(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0, target_resolution=1.0)
        assert_allclose(ds.grid.spacing, (1.0, 1.0))


class TestTargetResolutionIDL:
    """Test target_resolution parameter for IDL AMR reader."""

    def test_coarsens_output(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds = reader.read_timestep(IDL_AMR_DIR, 0, target_resolution=1.0)
        assert ds["B1"].shape == (16, 16)

    def test_none_is_finest(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds_default = reader.read_timestep(IDL_AMR_DIR, 0)
        ds_explicit = reader.read_timestep(IDL_AMR_DIR, 0, target_resolution=None)
        for name in ds_default.field_names():
            assert_allclose(ds_default[name], ds_explicit[name], rtol=1e-15)

    def test_preserves_uniform_density(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds = reader.read_timestep(IDL_AMR_DIR, 0, target_resolution=1.0)
        assert_allclose(ds["rho_m"], RHO0, rtol=1e-10)

    def test_preserves_harris_profile(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds = reader.read_timestep(IDL_AMR_DIR, 0, target_resolution=1.0)
        bx = ds["B1"]
        assert bx[:, -1].mean() > 0.9
        assert bx[:, 0].mean() < -0.9

    def test_no_nan_at_coarse_resolution(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds = reader.read_timestep(IDL_AMR_DIR, 0, target_resolution=1.0)
        for name in ds.field_names():
            assert not np.any(np.isnan(ds[name])), f"{name} contains NaN"

    def test_intermediate_snaps_to_nearest(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds = reader.read_timestep(IDL_AMR_DIR, 0, target_resolution=0.7)
        assert ds["B1"].shape == (32, 32)
        ds = reader.read_timestep(IDL_AMR_DIR, 0, target_resolution=0.8)
        assert ds["B1"].shape == (16, 16)


class TestSelectiveReadIDL:
    """Test selective field reading for IDL format."""

    def test_subset_returns_only_requested(self) -> None:
        reader, _ = open_batsrus(IDL_DIR)
        ds = reader.read_timestep(IDL_DIR, 0, fields=["B1", "rho_m"])
        assert set(ds.field_names()) == {"B1", "rho_m"}

    def test_subset_values_match_full(self) -> None:
        reader, _ = open_batsrus(IDL_DIR)
        ds_full = reader.read_timestep(IDL_DIR, 0)
        ds_sub = reader.read_timestep(IDL_DIR, 0, fields=["B1", "P"])
        assert_allclose(ds_sub["B1"], ds_full["B1"], rtol=1e-15)
        assert_allclose(ds_sub["P"], ds_full["P"], rtol=1e-15)

    def test_none_reads_all(self) -> None:
        reader, _ = open_batsrus(IDL_DIR)
        ds = reader.read_timestep(IDL_DIR, 0, fields=None)
        assert len(ds.field_names()) > 2


class TestSelectiveReadHDF5:
    """Test selective field reading for HDF5 BATL format."""

    def test_subset_returns_only_requested(self) -> None:
        reader, _ = open_batsrus(HDF5_DIR)
        ds = reader.read_timestep(HDF5_DIR, 0, fields=["B1", "rho_m"])
        assert set(ds.field_names()) == {"B1", "rho_m"}

    def test_subset_values_match_full(self) -> None:
        reader, _ = open_batsrus(HDF5_DIR)
        ds_full = reader.read_timestep(HDF5_DIR, 0)
        ds_sub = reader.read_timestep(HDF5_DIR, 0, fields=["B1", "P"])
        assert_allclose(ds_sub["B1"], ds_full["B1"], rtol=1e-15)
        assert_allclose(ds_sub["P"], ds_full["P"], rtol=1e-15)

    def test_none_reads_all(self) -> None:
        reader, _ = open_batsrus(HDF5_DIR)
        ds = reader.read_timestep(HDF5_DIR, 0, fields=None)
        assert len(ds.field_names()) > 2

    def test_single_field(self) -> None:
        reader, _ = open_batsrus(HDF5_DIR)
        ds = reader.read_timestep(HDF5_DIR, 0, fields=["rho_m"])
        assert ds.field_names() == ["rho_m"]


class TestIsUniformIDL:
    """Test the uniform grid detection helper."""

    def test_uniform(self) -> None:
        dx = np.full(100, 0.5)
        assert is_uniform_idl(dx) is True

    def test_amr(self) -> None:
        dx = np.array([0.5, 0.5, 1.0, 1.0])
        assert is_uniform_idl(dx) is False


class TestGeometryPropagation:
    """Geometry extracted from headers flows through to GridInfo."""

    def test_cartesian_geometry_propagates(self) -> None:
        _, config = open_batsrus(IDL_DIR)
        assert config.grid.geometry.type.value == "cartesian"

        reader_idl, _ = open_batsrus(IDL_DIR)
        ds_idl = reader_idl.read_timestep(IDL_DIR, 0)
        assert ds_idl.grid.geometry.type.value == "cartesian"

        reader_hdf, _ = open_batsrus(HDF5_DIR)
        ds_hdf = reader_hdf.read_timestep(HDF5_DIR, 0)
        assert ds_hdf.grid.geometry.type.value == "cartesian"

        config_param = parse_param_in(IDL_DIR / "PARAM.in")
        assert config_param.geometry == "cartesian"


class TestParamInSplitbDivb:
    """PARAM.in parsing for #SPLITB and #DIVB commands."""

    @pytest.mark.parametrize("use_splitb", [True, False])
    def test_splitb(self, tmp_path: Path, use_splitb: bool) -> None:
        flag = "T" if use_splitb else "F"
        (tmp_path / "PARAM.in").write_text(f"#SPLITB\n{flag}\t\tUseSplitB\n\n#END\n")
        config = parse_param_in(tmp_path / "PARAM.in")
        assert config.use_splitb is use_splitb

    def test_divb_method(self, tmp_path: Path) -> None:
        (tmp_path / "PARAM.in").write_text("#DIVB\nCT\t\tnDivBMethod\n\n#END\n")
        config = parse_param_in(tmp_path / "PARAM.in")
        assert config.divb_method == "CT"

    def test_splitb_in_physics_metadata(self, tmp_path: Path) -> None:
        (tmp_path / "PARAM.in").write_text(
            "#SPLITB\nT\t\tUseSplitB\n\n#DIVB\nCT8\t\tnDivBMethod\n\n#END\n"
        )
        from pypic.readers.batsrus._config import to_simulation_config

        config = parse_param_in(tmp_path / "PARAM.in")
        sim = to_simulation_config(config)
        assert sim.physics["use_splitb"] is True
        assert sim.physics["divb_method"] == "CT8"
