"""Tests for the BATSRUS reader using synthetic fixtures.

Fixtures are generated by ``scripts/generate_batsrus_fixture.py`` and
committed under ``tests/data/batsrus-synthetic/``.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
from numpy.testing import assert_allclose

from pypic.readers.batsrus import (
    open_batsrus,
    parse_header,
    parse_param_in,
)
from pypic.readers.batsrus._field_map import (
    FIELD_NAME_MAP,
    SKIP_FIELDS,
    convert_fields_to_si,
    is_normalized,
    unit_factor,
)
from pypic.readers.batsrus._grid import is_uniform_idl
from pypic.readers.batsrus._idl import read_out_file, read_out_header

DATA_DIR = Path(__file__).parent / "data" / "batsrus-synthetic"
IDL_DIR = DATA_DIR / "idl-uniform"
OUT_ASCII_DIR = DATA_DIR / "out-ascii"
OUT_BINARY_DIR = DATA_DIR / "out-binary"
HDF5_DIR = DATA_DIR / "hdf5-uniform"
AMR_DIR = DATA_DIR / "hdf5-amr"
IDL_AMR_DIR = DATA_DIR / "idl-amr"

# Harris sheet parameters (must match generate_batsrus_fixture.py)
B0 = 1.0
DELTA = 2.0
RHO0 = 1.0
P0 = 0.1
XMIN, XMAX = -8.0, 8.0
YMIN, YMAX = -8.0, 8.0
NX, NY = 16, 16
DX = (XMAX - XMIN) / NX


class TestFieldMap:
    """Unit tests for field name mapping and unit conversion."""

    def test_canonical_names_cover_mhd_basics(self) -> None:
        assert FIELD_NAME_MAP["Rho"] == "rho_m"
        assert FIELD_NAME_MAP["Bx"] == "B_1"
        assert FIELD_NAME_MAP["Ux"] == "V_1"
        assert FIELD_NAME_MAP["P"] == "P"

    def test_hyp_is_skipped(self) -> None:
        assert "Hyp" in SKIP_FIELDS

    def test_normalized_detection(self) -> None:
        assert is_normalized("normalized units")
        assert is_normalized("  Normalized  ")
        assert not is_normalized("Mp/cc km/s nT")

    @pytest.mark.parametrize(
        ("unit_str", "expected"),
        [
            ("nT", 1e-9),
            ("km/s", 1e3),
            ("nPa", 1e-9),
            ("R", 1.0),
        ],
    )
    def test_unit_factor(self, unit_str: str, expected: float) -> None:
        assert_allclose(unit_factor(unit_str), expected, rtol=1e-10)

    def test_density_to_si(self) -> None:
        from scipy import constants

        factor = unit_factor("Mp/cc")
        rho_mpccc = 5.0
        rho_si = rho_mpccc * factor
        expected = 5.0 * 1e6 * constants.m_p
        assert_allclose(rho_si, expected, rtol=1e-10)

    def test_convert_fields_noop_for_normalized(self) -> None:
        fields = {"rho_m": np.array([1.0, 2.0])}
        var_names = ("Rho",)
        unit_names = ("normalized",)
        result = convert_fields_to_si(fields, var_names, unit_names)
        assert_allclose(result["rho_m"], [1.0, 2.0])

    def test_convert_fields_applies_factors(self) -> None:
        fields = {"B_1": np.array([5.0])}
        var_names = ("Bx",)
        unit_names = ("nT",)
        result = convert_fields_to_si(fields, var_names, unit_names)
        assert_allclose(result["B_1"], [5e-9], rtol=1e-10)


class TestHeader:
    """Test .h header parsing."""

    def test_parse_synthetic_header(self) -> None:
        header = parse_header(IDL_DIR / "z=0_mhd_1_n00000000.h")
        assert header.ndim == 2
        assert header.geometry == "cartesian"
        assert header.n_cells == NX * NY
        assert header.is_binary is True
        assert header.n_byte_real == 8
        assert header.n_plot_var == 12
        assert "Rho" in header.var_names
        assert "Bx" in header.var_names

    def test_header_domain_bounds(self) -> None:
        header = parse_header(IDL_DIR / "z=0_mhd_1_n00000000.h")
        assert_allclose(header.domain_min, (XMIN, YMIN))
        assert_allclose(header.domain_max, (XMAX, YMAX))

    def test_header_gamma_parameter(self) -> None:
        header = parse_header(IDL_DIR / "z=0_mhd_1_n00000000.h")
        assert header.n_param == 1
        assert_allclose(header.param_values[0], 5.0 / 3.0, rtol=1e-4)


class TestParamIn:
    """Test PARAM.in parsing."""

    def test_parse_synthetic_param(self) -> None:
        config = parse_param_in(IDL_DIR / "PARAM.in")
        assert config.io_units == "NONE"
        assert config.normalization_type == "NONE"
        assert_allclose(config.gamma, 5.0 / 3.0, rtol=1e-10)

    def test_grid_bounds(self) -> None:
        config = parse_param_in(IDL_DIR / "PARAM.in")
        assert_allclose(config.domain_min[:2], (XMIN, YMIN))
        assert_allclose(config.domain_max[:2], (XMAX, YMAX))


class TestIDLUniform:
    """Test IDL per-cell reader with uniform synthetic grid."""

    def test_reads_with_canonical_names_and_shapes(self) -> None:
        reader, _ = open_batsrus(IDL_DIR)
        ds = reader.read_timestep(IDL_DIR, 0)
        assert ds.has_field("B_1")
        assert ds.has_field("rho_m")
        assert ds.has_field("V_1")
        assert ds.has_field("P")
        assert not ds.has_field("Hyp")
        for name in ds.field_names():
            assert ds[name].shape == (NX, NY), f"{name} has wrong shape"

    def test_harris_physics(self) -> None:
        reader, _ = open_batsrus(IDL_DIR)
        ds = reader.read_timestep(IDL_DIR, 0)
        # Harris Bx profile
        bx = ds["B_1"]
        iy_mid = NY // 2
        assert_allclose(bx[:, iy_mid], 0.0, atol=0.3)
        assert bx[:, -1].mean() > 0.9
        assert bx[:, 0].mean() < -0.9
        # Uniform density and pressure
        assert_allclose(ds["rho_m"], RHO0, rtol=1e-10)
        assert_allclose(ds["P"], P0, rtol=1e-10)

    def test_grid_info(self) -> None:
        _, config = open_batsrus(IDL_DIR)
        assert config.grid.dimensions == (NX, NY)
        assert_allclose(config.grid.spacing, (DX, DX))

    def test_no_nan_fields(self) -> None:
        reader, _ = open_batsrus(IDL_DIR)
        ds = reader.read_timestep(IDL_DIR, 0)
        for name in ds.field_names():
            assert not np.any(np.isnan(ds[name])), f"{name} contains NaN"

    def test_available_fields_matches_read(self) -> None:
        """Lightweight probe returns the same fields as a full read."""
        reader, _ = open_batsrus(IDL_DIR)
        ds = reader.read_timestep(IDL_DIR, 0)
        probed = reader.available_fields(IDL_DIR, 0)
        assert probed == sorted(ds.field_names())


class TestHDF5Uniform:
    """Test HDF5 BATL reader with uniform synthetic grid."""

    def test_reads_with_correct_shapes_no_nan(self) -> None:
        reader, _ = open_batsrus(HDF5_DIR)
        ds = reader.read_timestep(HDF5_DIR, 0)
        for name in ds.field_names():
            assert ds[name].shape == (NX, NY), f"{name} has wrong shape"
            assert not np.any(np.isnan(ds[name])), f"{name} contains NaN"

    def test_available_fields_matches_read(self) -> None:
        """Lightweight probe returns the same fields as a full read."""
        reader, _ = open_batsrus(HDF5_DIR)
        ds = reader.read_timestep(HDF5_DIR, 0)
        probed = reader.available_fields(HDF5_DIR, 0)
        assert probed == sorted(ds.field_names())

    def test_cross_format_match_idl(self) -> None:
        """IDL and HDF5 produce identical fields for the same physics."""
        reader_idl, _ = open_batsrus(IDL_DIR)
        reader_hdf, _ = open_batsrus(HDF5_DIR)
        ds_idl = reader_idl.read_timestep(IDL_DIR, 0)
        ds_hdf = reader_hdf.read_timestep(HDF5_DIR, 0)

        for name in ds_idl.field_names():
            if not ds_hdf.has_field(name):
                continue
            assert_allclose(
                ds_idl[name],
                ds_hdf[name],
                rtol=1e-10,
                err_msg=f"Cross-format mismatch for {name}",
            )


class TestHDF5AMR:
    """Test HDF5 BATL reader with AMR regridding."""

    def test_output_at_finest_resolution(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0)
        # Finest dx = 0.5, domain = 16x16 -> 32x32
        assert ds["B_1"].shape == (32, 32)

    def test_no_nan_after_regrid(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0)
        for name in ds.field_names():
            assert not np.any(np.isnan(ds[name])), f"{name} contains NaN"

    def test_coarse_cells_filled(self) -> None:
        """Coarse cells are expanded via nearest-neighbor fill."""
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0)
        rho = ds["rho_m"]
        # All cells should have the uniform density value
        assert_allclose(rho, RHO0, rtol=1e-10)

    def test_harris_profile_preserved(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0)
        bx = ds["B_1"]
        # Top row should be near +B0
        assert bx[:, -1].mean() > 0.9
        # Bottom row should be near -B0
        assert bx[:, 0].mean() < -0.9


class TestOpenBatsrusDetection:
    """Test format auto-detection in ``open_batsrus``."""

    def test_detects_idl(self) -> None:
        _, config = open_batsrus(IDL_DIR)
        assert config.model_name == "BATSRUS"
        assert config.model_type == "MHD"

    def test_detects_hdf5(self) -> None:
        _, config = open_batsrus(HDF5_DIR)
        assert config.model_name == "BATSRUS"

    def test_available_timesteps_idl(self) -> None:
        reader, _ = open_batsrus(IDL_DIR)
        steps = reader.available_timesteps(IDL_DIR)
        assert 0 in steps

    def test_available_timesteps_hdf5(self) -> None:
        reader, _ = open_batsrus(HDF5_DIR)
        steps = reader.available_timesteps(HDF5_DIR)
        assert 0 in steps

    def test_empty_dir_raises_file_not_found(self, tmp_path) -> None:  # type: ignore[no-untyped-def]
        """Convention (Unit 6): missing-output → FileNotFoundError."""
        with pytest.raises(FileNotFoundError, match="No BATSRUS output"):
            open_batsrus(tmp_path)


class TestIDLAMR:
    """Test IDL per-cell reader with AMR synthetic grid."""

    def test_output_at_finest_resolution(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds = reader.read_timestep(IDL_AMR_DIR, 0)
        assert ds["B_1"].shape == (32, 32)

    def test_no_nan_after_regrid(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds = reader.read_timestep(IDL_AMR_DIR, 0)
        for name in ds.field_names():
            assert not np.any(np.isnan(ds[name])), f"{name} contains NaN"

    def test_uniform_density(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds = reader.read_timestep(IDL_AMR_DIR, 0)
        assert_allclose(ds["rho_m"], RHO0, rtol=1e-10)


class TestTargetResolutionHDF5:
    """Test target_resolution parameter for HDF5 AMR reader."""

    def test_coarsens_output(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0, target_resolution=1.0)
        assert ds["B_1"].shape == (16, 16)

    def test_none_is_finest(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds_default = reader.read_timestep(AMR_DIR, 0)
        ds_explicit = reader.read_timestep(AMR_DIR, 0, target_resolution=None)
        for name in ds_default.field_names():
            assert_allclose(ds_default[name], ds_explicit[name], rtol=1e-15)

    def test_preserves_uniform_density(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0, target_resolution=1.0)
        assert_allclose(ds["rho_m"], RHO0, rtol=1e-10)

    def test_preserves_harris_profile(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0, target_resolution=1.0)
        bx = ds["B_1"]
        assert bx[:, -1].mean() > 0.9
        assert bx[:, 0].mean() < -0.9

    def test_no_nan_at_coarse_resolution(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0, target_resolution=1.0)
        for name in ds.field_names():
            assert not np.any(np.isnan(ds[name])), f"{name} contains NaN"

    def test_intermediate_snaps_to_nearest(self) -> None:
        """A target_resolution between levels snaps to the nearest valid dx."""
        reader, _ = open_batsrus(AMR_DIR)
        # Levels are 0.5 and 1.0. Target 0.7 is closer to 0.5.
        ds = reader.read_timestep(AMR_DIR, 0, target_resolution=0.7)
        assert ds["B_1"].shape == (32, 32)
        # Target 0.8 is closer to 1.0.
        ds = reader.read_timestep(AMR_DIR, 0, target_resolution=0.8)
        assert ds["B_1"].shape == (16, 16)

    def test_grid_spacing_matches_target(self) -> None:
        reader, _ = open_batsrus(AMR_DIR)
        ds = reader.read_timestep(AMR_DIR, 0, target_resolution=1.0)
        assert_allclose(ds.grid.spacing, (1.0, 1.0))


class TestTargetResolutionIDL:
    """Test target_resolution parameter for IDL AMR reader."""

    def test_coarsens_output(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds = reader.read_timestep(IDL_AMR_DIR, 0, target_resolution=1.0)
        assert ds["B_1"].shape == (16, 16)

    def test_none_is_finest(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds_default = reader.read_timestep(IDL_AMR_DIR, 0)
        ds_explicit = reader.read_timestep(IDL_AMR_DIR, 0, target_resolution=None)
        for name in ds_default.field_names():
            assert_allclose(ds_default[name], ds_explicit[name], rtol=1e-15)

    def test_preserves_uniform_density(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds = reader.read_timestep(IDL_AMR_DIR, 0, target_resolution=1.0)
        assert_allclose(ds["rho_m"], RHO0, rtol=1e-10)

    def test_preserves_harris_profile(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds = reader.read_timestep(IDL_AMR_DIR, 0, target_resolution=1.0)
        bx = ds["B_1"]
        assert bx[:, -1].mean() > 0.9
        assert bx[:, 0].mean() < -0.9

    def test_no_nan_at_coarse_resolution(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds = reader.read_timestep(IDL_AMR_DIR, 0, target_resolution=1.0)
        for name in ds.field_names():
            assert not np.any(np.isnan(ds[name])), f"{name} contains NaN"

    def test_intermediate_snaps_to_nearest(self) -> None:
        reader, _ = open_batsrus(IDL_AMR_DIR)
        ds = reader.read_timestep(IDL_AMR_DIR, 0, target_resolution=0.7)
        assert ds["B_1"].shape == (32, 32)
        ds = reader.read_timestep(IDL_AMR_DIR, 0, target_resolution=0.8)
        assert ds["B_1"].shape == (16, 16)


class TestSelectiveReadIDL:
    """Test selective field reading for IDL format."""

    def test_subset_returns_only_requested(self) -> None:
        reader, _ = open_batsrus(IDL_DIR)
        ds = reader.read_timestep(IDL_DIR, 0, fields=["B_1", "rho_m"])
        assert set(ds.field_names()) == {"B_1", "rho_m"}

    def test_subset_values_match_full(self) -> None:
        reader, _ = open_batsrus(IDL_DIR)
        ds_full = reader.read_timestep(IDL_DIR, 0)
        ds_sub = reader.read_timestep(IDL_DIR, 0, fields=["B_1", "P"])
        assert_allclose(ds_sub["B_1"], ds_full["B_1"], rtol=1e-15)
        assert_allclose(ds_sub["P"], ds_full["P"], rtol=1e-15)

    def test_none_reads_all(self) -> None:
        reader, _ = open_batsrus(IDL_DIR)
        ds = reader.read_timestep(IDL_DIR, 0, fields=None)
        assert len(ds.field_names()) > 2


class TestSelectiveReadHDF5:
    """Test selective field reading for HDF5 BATL format."""

    def test_subset_returns_only_requested(self) -> None:
        reader, _ = open_batsrus(HDF5_DIR)
        ds = reader.read_timestep(HDF5_DIR, 0, fields=["B_1", "rho_m"])
        assert set(ds.field_names()) == {"B_1", "rho_m"}

    def test_subset_values_match_full(self) -> None:
        reader, _ = open_batsrus(HDF5_DIR)
        ds_full = reader.read_timestep(HDF5_DIR, 0)
        ds_sub = reader.read_timestep(HDF5_DIR, 0, fields=["B_1", "P"])
        assert_allclose(ds_sub["B_1"], ds_full["B_1"], rtol=1e-15)
        assert_allclose(ds_sub["P"], ds_full["P"], rtol=1e-15)

    def test_none_reads_all(self) -> None:
        reader, _ = open_batsrus(HDF5_DIR)
        ds = reader.read_timestep(HDF5_DIR, 0, fields=None)
        assert len(ds.field_names()) > 2

    def test_single_field(self) -> None:
        reader, _ = open_batsrus(HDF5_DIR)
        ds = reader.read_timestep(HDF5_DIR, 0, fields=["rho_m"])
        assert ds.field_names() == ["rho_m"]


class TestIsUniformIDL:
    """Test the uniform grid detection helper."""

    def test_uniform(self) -> None:
        dx = np.full(100, 0.5)
        assert is_uniform_idl(dx) is True

    def test_amr(self) -> None:
        dx = np.array([0.5, 0.5, 1.0, 1.0])
        assert is_uniform_idl(dx) is False


class TestGeometryPropagation:
    """Geometry extracted from headers flows through to GridInfo."""

    def test_cartesian_geometry_propagates(self) -> None:
        _, config = open_batsrus(IDL_DIR)
        assert config.grid.geometry.type.value == "cartesian"

        reader_idl, _ = open_batsrus(IDL_DIR)
        ds_idl = reader_idl.read_timestep(IDL_DIR, 0)
        assert ds_idl.grid.geometry.type.value == "cartesian"

        reader_hdf, _ = open_batsrus(HDF5_DIR)
        ds_hdf = reader_hdf.read_timestep(HDF5_DIR, 0)
        assert ds_hdf.grid.geometry.type.value == "cartesian"

        config_param = parse_param_in(IDL_DIR / "PARAM.in")
        assert config_param.geometry == "cartesian"


class TestParamInSplitbDivb:
    """PARAM.in parsing for #SPLITB and #DIVB commands."""

    @pytest.mark.parametrize("use_splitb", [True, False])
    def test_splitb(self, tmp_path: Path, use_splitb: bool) -> None:
        flag = "T" if use_splitb else "F"
        (tmp_path / "PARAM.in").write_text(f"#SPLITB\n{flag}\t\tUseSplitB\n\n#END\n")
        config = parse_param_in(tmp_path / "PARAM.in")
        assert config.use_splitb is use_splitb

    def test_divb_method(self, tmp_path: Path) -> None:
        (tmp_path / "PARAM.in").write_text("#DIVB\nCT\t\tnDivBMethod\n\n#END\n")
        config = parse_param_in(tmp_path / "PARAM.in")
        assert config.divb_method == "CT"

    def test_splitb_in_physics_metadata(self, tmp_path: Path) -> None:
        (tmp_path / "PARAM.in").write_text(
            "#SPLITB\nT\t\tUseSplitB\n\n#DIVB\nCT8\t\tnDivBMethod\n\n#END\n"
        )
        from pypic.readers.batsrus._config import to_simulation_config

        config = parse_param_in(tmp_path / "PARAM.in")
        sim = to_simulation_config(config)
        assert sim.physics.extra["use_splitb"] is True
        assert sim.physics.extra["divb_method"] == "CT8"


class TestMergedOut:
    """Merged ``.out`` snapshots, ASCII and real8 binary.

    These fixtures carry the same Harris-sheet physics as ``idl-uniform``,
    so the three read paths must agree field-for-field. Before this suite
    existed the ``.out`` listing path called ``parse_header`` (the ``.h``
    text parser), which returned no variable names for ASCII input and
    raised ``UnicodeDecodeError`` on binary input.
    """

    @pytest.mark.parametrize("out_dir", [OUT_ASCII_DIR, OUT_BINARY_DIR])
    def test_available_fields_matches_what_read_produces(self, out_dir: Path) -> None:
        reader, _ = open_batsrus(out_dir)
        listed = set(reader.available_fields(out_dir, 0))
        read = set(reader.read_timestep(out_dir, 0).field_names())
        assert listed == read

    def test_binary_out_listing_does_not_decode_as_text(self) -> None:
        """A real8 ``.out`` is not UTF-8; listing must not try to read it as text."""
        reader, _ = open_batsrus(OUT_BINARY_DIR)
        mapping = reader.available_fields_mapping(OUT_BINARY_DIR, 0)
        assert mapping["B_1"] == "Bx"

    def test_header_only_read_matches_full_read(self) -> None:
        """``read_out_header`` is the same extractor the data path uses."""
        names_only, _ = read_out_header(OUT_BINARY_DIR / "z=0_mhd_1_n00000000.out")
        _, _, names_full, _ = read_out_file(OUT_BINARY_DIR / "z=0_mhd_1_n00000000.out")
        assert names_only == names_full

    @pytest.mark.parametrize("field", ["B_1", "B_2", "rho_m", "P", "V_1", "J_3"])
    def test_out_agrees_with_idl_on_identical_physics(self, field: str) -> None:
        """The ``.out`` path applies the same unit handling as ``.idl``.

        ``_read_out`` used to skip the SI conversion both sibling paths
        perform, so the same run read through two formats disagreed.
        """
        idl_reader, _ = open_batsrus(IDL_DIR)
        out_reader, _ = open_batsrus(OUT_ASCII_DIR)
        idl = idl_reader.read_timestep(IDL_DIR, 0)
        out = out_reader.read_timestep(OUT_ASCII_DIR, 0)
        assert_allclose(np.asarray(out[field]), np.asarray(idl[field]), rtol=1e-12)

    @pytest.mark.parametrize("field", ["B_1", "rho_m", "P"])
    def test_ascii_and_binary_out_agree(self, field: str) -> None:
        ascii_reader, _ = open_batsrus(OUT_ASCII_DIR)
        binary_reader, _ = open_batsrus(OUT_BINARY_DIR)
        a = ascii_reader.read_timestep(OUT_ASCII_DIR, 0)
        b = binary_reader.read_timestep(OUT_BINARY_DIR, 0)
        assert_allclose(np.asarray(a[field]), np.asarray(b[field]), rtol=1e-12)

    def test_grid_spacing_is_measured_along_each_axis(self) -> None:
        """Spacing per axis, not ``.flat[1] - .flat[0]``, which walks the last axis."""
        reader, _ = open_batsrus(OUT_ASCII_DIR)
        ds = reader.read_timestep(OUT_ASCII_DIR, 0)
        assert_allclose(ds.grid.spacing, (1.0, 1.0), rtol=1e-12)

    def test_read_populates_simulation_config(self) -> None:
        """``.out`` sets ``_sim_config`` like both sibling paths."""
        reader, _ = open_batsrus(OUT_ASCII_DIR)
        reader.read_timestep(OUT_ASCII_DIR, 0)
        assert reader._sim_config is not None


class TestParseHeaderFailsLoud:
    """``parse_header`` must reject input that is not a BATSRUS ``.h``."""

    def test_rejects_file_without_sections(self, tmp_path: Path) -> None:
        stray = tmp_path / "notaheader.h"
        stray.write_text("#ifndef FOO_H\n#define FOO_H\n#endif\n")
        with pytest.raises(ValueError, match="BATSRUS"):
            parse_header(stray)


class TestSimulationTomlReachesDataset:
    """The merged ``simulation.toml`` must shape what ``read`` returns."""

    TOML = """\
[schema]
version = "1.0"

[model]
name = "BATSRUS"
type = "MHD"

[run]
name = "toml-run"

[time]
dt = 0.1
t_start = 0.0
t_end = 1.0
n_steps = 10

[grid]
dimensions = [16, 16]
spacing = [1.0, 1.0]
lower = [-8.0, -8.0]
upper = [8.0, 8.0]

[units]
system = "MHD"
reference_length = 6.371e6
reference_density = 1.67e-17
reference_b_field = 5.0e-9

[coordinates]
geometry = "cartesian"
frame = "GSE"

[[species]]
name = "p"
charge = 1.0
mass = 1.0
"""

    @pytest.fixture
    def toml_dir(self, tmp_path: Path) -> Path:
        import shutil

        d = tmp_path / "idl"
        shutil.copytree(IDL_DIR, d)
        (d / "simulation.toml").write_text(self.TOML)
        return d

    def test_frame_normalization_and_run_flow_to_dataset(self, toml_dir: Path):
        from pypic import open_simulation

        plain = open_batsrus(IDL_DIR)[0].read_timestep(IDL_DIR, 0)
        sim = open_simulation(toml_dir)
        ds = sim.read(0)
        assert ds.frame == "GSE"
        assert ds.normalization.b_field_ref == 5.0e-9
        assert ds.metadata["run"].name == "toml-run"
        # SI arrays are normalized into code units by the declared references
        assert_allclose(ds["B_1"], plain["B_1"] / 5.0e-9, rtol=1e-12)

    def test_ambiguous_step_files_raise(self, tmp_path: Path):
        import shutil

        d = tmp_path / "idl"
        shutil.copytree(IDL_DIR, d)
        header = next(d.glob("*.h"))
        shutil.copy(header, d / header.name.replace("mhd_1", "mhd_2"))
        reader, _ = open_batsrus(d)
        with pytest.raises(ValueError, match="Ambiguous"):
            reader.read_timestep(d, 0)
