"""pypic: read, analyze, and plot plasma simulation output."""

__version__ = "0.1.0"

from pypic.coordinates import (
    CARTESIAN,
    CYLINDRICAL,
    SPHERICAL,
    CoordinateGeometry,
    GeometryType,
)
from pypic.derived import (
    agyrotropy,
    alfven_mach,
    alfven_speed,
    current_density_magnitude,
    debye_length,
    electric_energy_density,
    electric_field_magnitude,
    enthalpy,
    entropy,
    gyrofrequency,
    gyroradius,
    gyrotropic_entropy,
    internal_energy_density,
    ion_acoustic_speed,
    kinetic_energy_density,
    magnetic_energy_density,
    magnetic_field_magnitude,
    magnetosonic_mach,
    magnetosonic_speed,
    parallel_pressure,
    perpendicular_pressure,
    plasma_beta,
    plasma_frequency,
    poynting_flux,
    relativistic_enthalpy,
    skin_depth,
    sound_speed,
    thermal_energy_density,
    thermal_speed,
    velocity_magnitude,
)
from pypic.readers import FieldDataset, GridInfo, load_config
from pypic.units import Normalization, PhysicsConstants, SpeciesInfo

__all__ = [
    "CARTESIAN",
    "CYLINDRICAL",
    "SPHERICAL",
    "CoordinateGeometry",
    "FieldDataset",
    "GeometryType",
    "GridInfo",
    "Normalization",
    "PhysicsConstants",
    "SpeciesInfo",
    "agyrotropy",
    "alfven_mach",
    "alfven_speed",
    "current_density_magnitude",
    "debye_length",
    "electric_energy_density",
    "electric_field_magnitude",
    "enthalpy",
    "entropy",
    "gyrofrequency",
    "gyroradius",
    "gyrotropic_entropy",
    "internal_energy_density",
    "ion_acoustic_speed",
    "kinetic_energy_density",
    "load_config",
    "magnetic_energy_density",
    "magnetic_field_magnitude",
    "magnetosonic_mach",
    "magnetosonic_speed",
    "parallel_pressure",
    "perpendicular_pressure",
    "plasma_beta",
    "plasma_frequency",
    "poynting_flux",
    "relativistic_enthalpy",
    "skin_depth",
    "sound_speed",
    "thermal_energy_density",
    "thermal_speed",
    "velocity_magnitude",
]
